### ISSUE TITLE
npm run dev not work

### ISSUE THREAD

**Issue by fatemehqasemkhani** [yogaboll/react-npm-component-starter#9]
**error:**
> react-component-example-project@0.1.0 dev D:\react-npm-component-starter
> concurrently "npm run lib:watch" "npm run docs"

[1]
[1] > react-component-example-project@0.1.0 docs D:\react-npm-component-starter
[1] > webpack-dev-server --mode development
[1]
[0]
[0] > react-component-example-project@0.1.0 lib:watch D:\react-npm-component-starte                                                                                                                                                                                            r
[0] > babel src/lib -w -d lib --copy-files
[0]
[0] Successfully compiled 1 file with Babel.
[1] D:\react-npm-component-starter\node_modules\webpack-cli\bin\config-yargs.js:89
[1]                             describe: optionsSchema.definitions.output.properti                                                                                                                                                                                            es.path.description,
[1]                                                                        ^
[1]
[1] TypeError: Cannot read property 'properties' of undefined
[1]     at module.exports (D:\react-npm-component-starter\node_modules\webpack-cli\                                                                                                                                                                                            bin\config-yargs.js:89:48)
[1]     at Object.<anonymous> (D:\react-npm-component-starter\node_modules\webpack-                                                                                                                                                                                            dev-server\bin\webpack-dev-server.js:84:40)
[1]     at Module._compile (module.js:652:30)
[1]     at Object.Module._extensions..js (module.js:663:10)
[1]     at Module.load (module.js:565:32)
[1]     at tryModuleLoad (module.js:505:12)
[1]     at Function.Module._load (module.js:497:3)
[1]     at Function.Module.runMain (module.js:693:10)
[1]     at startup (bootstrap_node.js:191:16)
[1]     at bootstrap_node.js:612:3
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! react-component-example-project@0.1.0 docs: `webpack-dev-server --mode                                                                                                                                                                                             development`
[1] npm ERR! Exit status 1
[1] npm ERR!
npm ERR! Failed at the react-component-example-project@0.1.0 docs script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional lo                                                                                                                                                                                            gging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     C:\Users\fghasemkhani\AppData\Roaming\npm-cache\_logs\2018-10-04T0                                                                                                                                                                                            6_43_52_206Z-debug.log
[1] npm run docs exited with code 1

**Comment by wafo** [comment]
Try updating your _webpack-cli_ in your package.json and run _npm install_ again. That fixed it for me.

`"webpack-cli": "^3.1.1",`

**Comment by fatemehqasemkhani** [comment]
thanks a lot.

**Comment by markusenglund** [comment]
Updated the repo now with the new version of webpack-cli. Thanks @elWafo.
